name: epicPlg
version: 1.0
author: MortenN
main: com.morten.epicPlugin.EpicMain
api-version: 1.14

commands:
  sand:
    description: Sleep toggle if night
    usage: /<command>
  mobFarmLoot:
    description: Displays help page
    usage: /<command>
  mobFarmLoot ON:
    description: Enables mobFarmLoot
    usage: /<command>
  mobFarmLoot OFF:
    description: Disables mobFarmLoot
    usage: /<command>
  mobFarmLoot List:
    description: Disables mobFarmLoot
    usage: /<command>
  sleep:
    description: Sleep command
    usage: /<command>
  autofish:
    description: autofish command
    usage: /<command>
