name: epicPlg
version: 1.0
author: MortenN
main: com.morten.epicPlugin.EpicMain
api-version: 1.14

commands:
  sand:
    description: Sleep toggle if night
    usage: /<command>
  mobFarmLootOn:
    description: Sleep toggle if night
    usage: /<command>
  mobFarmLootOff:
    description: Sleep toggle if night
    usage: /<command>
  sleep:
    description: Sleep command
    usage: /<command>
  autofish:
    description: autofish command
    usage: /<command>
